### PR TITLE
Added support for many AMD64 VEX conditional calls

### PR DESCRIPTION
**Pull request by dnivra**
This pull request mainly adds support for many AMD64 VEX conditional calls. There are couple of conditional calls and operations/conditions in specific conditional calls that are still not supported(they'll be dirty statements). But these changes should hopefully improve lifting to AIL.

### CODE REVIEW

**Comment by ltfish** [comment]
Amazing - I totally forgot about this PR! Let me take a look at this PR this week.

**Comment by dnivra** [comment]
Rebased on current master and resolved all merge conflicts. The major conflict was with #40, which implemented the same as eadc2a4 but differently. Also, pushed some more changes needed after the angr VEX engine refactor.

However, more changes are needed before merging. All `BinaryOp`s need fixing to reflect changes in #40. Fixing those will fix many of the linter issues and one of the failed test cases. I'm not sure when I'll get down to taking a look at them though since I'll have to revisit the VEX engine again to make sense what `signed` should be set to in each of the `BinaryOp`s. I haven't investigated the other failing test case yet and the other lint errors don't make sense to me. I'll take a look again sometime.

**Comment by ltfish** [comment]
Awesome! I'm happy that you are rebasing this branch on the latest master.

**Comment by rhelmot** [comment]
This is still important, right?

**Comment by ltfish** [comment]
I implemented it in angr instead. This is no longer relevant.

**Pull request closed without merging**
